import {Platform, Dimensions} from 'react-native';

const {winW, winH} = Dimensions.get('window');

const AndroidStyles = {
    regText1: {fontSize: 20, color: '#000', fontWeight: 'bold'},
    regText2: {fontSize: 16, color: '#000'},

    introWrap: {justifyContent: 'center', alignItems: 'center'},
    introImg: {flex: 1, width: null, height: null, resizeMode: "stretch"},
    posAbsolute: {flex: 1, position: 'absolute', top: 0, bottom: 0, left: 0, right: 0},
    introSkip: {borderColor: "#ffffff", borderWidth: 1, borderRadius: 15},
    introPaging: {position: 'absolute', bottom: 100},
    pAbsHome: {position: 'absolute', top: 0, bottom: 0, left: 0, right: 0},
    pAbsIntro: {position: 'absolute', top: 80, bottom: 0, left: 0, right: 0},


    ///sravan

    fFamily: {fontFamily: 'Muli-Regular'},

    //PRAVEEN ADDED STYLES
    PackageInput: {fontSize: 16,},
    PackageText: {fontSize: 18, marginHorizontal: 5,},


    //praveen styles
    cBlk: {color: '#000000'},
    cWhite: {color: '#FFF'},
    cAsh: {color: '#b2beb5'},
    cDCyan: {color: '#018fae'},
    cRed: {color: '#FF0000'},
    cDarkRed: {color: '#C91A1F'},
    cBlue: {color: '#1e90ff'},
    cOrng: {color: '#FFA500'},
    cOrangered: {color: '#FF4500'},
    cGrey: {color:'#808080'},
    colorBlue:{color:'#233167'},
    cDarkBlue:{color:'#0D276B'},
    cLightBlue:{color:'#516496'},
    cLightNavyBlue:{color:'#1F59DD'},
    colorLblue:{color:'#848CAA'},
    colorRed:{color:'#C91A1F'},
    colorGreen:{color:'#36A84C'},
    colorLWhite:{color:'#EFF0FF'},
    colorOrangeYellow:{color:'#f3cc14'},
    cRedBlack:{color:'#8b0000'},
    cDisabled:{color:'#cccccc'},
    cLightGreen:{color:'#94ff66'},
    cBlueGreenMix:{color:'#db99ff'},
    cVoiletPinkMix:{color:'#CF268A'},
    cLightGrey:{color:'#737373'},
    cBlue2:{color:'#2D9CDB'},
    cOrange:{color:'#F2994A'},
    cBlack68:{color:'rgba(0, 0, 0, 0.68)'},
    cBlack87:{color:'rgba(0, 0, 0, 0.87)'},
    cGrey33:{color:'#333333'},
    cGrey4F:{color:'#4F4F4F'},
    cLightRed:{color:'#EB5757'},
    cLightWhite:{color:'#f2f2f2'},
    bcLGoldenrod:{color:'#FFD365'},


    pAbsolute: {position: 'absolute'},
    NotificationPosAbsolute: { position: 'absolute', bottom: 10, right: 10},
    HomeScreenCountsPosAb: { position: 'absolute', top: -8, right: 0},
    HomeScreenLeftCountsPosAb: { position: 'absolute', top: -8, left: 0},
    posAbsoluteChip: {flex: 1, position: 'absolute', top: 5, right: 10, bottom: 0},
    posAbsoluteKidChip: {flex: 1, position: 'absolute', top: 15, right: 10},
    Btm0: {bottom: 0},


    bcBlk: {borderColor: '#000'},
    bcLYellow: {borderColor: '#fae7a8'},
    bcOrangeYellow: {borderColor: '#f3cc14'},
    bcOrng: {borderColor: '#FFA500'},
    bcOrangered: {borderColor: '#FF4500'},
    bcRed: {borderColor: '#FF0000'},
    bcAsh: {borderColor: '#b2beb5'},
    bcGrey: {borderColor: '#808080'},
    bcWhite: {borderColor: '#FFF'},
    bcDWhite: {borderColor: '#f1f5f4'},
    bcGreen:{borderColor:'#36A84C'},
    bcBlue:{borderColor:'#233167'},
    bcBlue2:{borderColor:'#2D9CDB'},
    bcLBlue:{borderColor:'#E0E0FF'},
    bcLightBlue:{borderColor:'#3AAAF6'},
    bcLightRed:{borderColor:'#EB5757'},
    bcLightWhite:{borderColor:'rgba(0,0,0,0.1)'},
    bcLightAsh:{borderColor:'#cccccc'},
    bcDisabled:{borderColor:'#cccccc'},

    bgTransprent: {backgroundColor: 'rgba(0,0,0,0.3)'},
    bgLTransprent: {backgroundColor: 'rgba(0,0,0,0.1)'},
    bgDarkTransprent: {backgroundColor: 'rgba(0,0,0,0.9)'},
    bgRedTransprent: {backgroundColor: 'rgba(255,0,0,0.1)'},
    bgRed: {backgroundColor: '#FF0000'},
    bgAsh: {backgroundColor: '#b2beb5'},
    bgDarkRed: {backgroundColor: '#C91A1F'},
    bgDBlue: {backgroundColor: '#3b5998'},
     bgLGrey: {backgroundColor: '#DCDCDC'},
    bgWhite: {backgroundColor: '#FFFFFF'},
    bgDWhite: {backgroundColor: '#f1f5f4'},
    bgLYellow: {backgroundColor: '#fae7a8'},
    bgOrangeYellow: {backgroundColor: '#f3cc14'},
    bgDisabled: {backgroundColor: '#cccccc'},
    bgLWhite: {backgroundColor: '#EFF0FF'},
    bgLBlue: {backgroundColor: '#848CAA'},
    defaultbgColor:{backgroundColor:'#C91A1F'},
    bgLPink:{backgroundColor:'#FFDDDD'},
    bgLSandStone:{backgroundColor:'#DBD0CC'},
    bgLBronziel:{backgroundColor:'#E1CDAE'},
    bgLGoldenrod:{backgroundColor:'#FFD365'},
    dgLWhite:{backgroundColor:'#f2f2f2'},
    bgPureRed:{backgroundColor:'#db2b30'},
    bgBlueGreenMix:{backgroundColor:'#14c9cb'},
    bgLPurple:{backgroundColor:'#CBC3E3'},
    bgDullYellow:{backgroundColor:'#f7e39a'},
    bgLightVoilet:{backgroundColor:'#e4b7d4'},
    bgLightRed:{backgroundColor:'#EB5757'},
    bgLGreenWhiteMix:{backgroundColor:'#a1d9d8'},
    cardColors :['#f7e39a', '#fece79', '#f8a555',
        '#f48270', '#f27f93', '#f192bb',
        '#e4b7d4', '#8c8bc4', '#90c9e2',
        '#a1d9d8', '#98d0a9', '#c0d682'],

    //light background colors

    bgLGreen: {backgroundColor: '#ccf6d8'},
    bgLBlueGreen: {backgroundColor: '#a1d9d8'},
    bgLBrown: {backgroundColor: '#f1e9c2'},
    bgLVoilet: {backgroundColor: '#dce3fd'},
    bgLYellow2: {backgroundColor: '#FFFFCC'},
    bgTEST: {backgroundColor: '#FFFFCC'},



    bgfae: {backgroundColor: '#018fae'},
    bgDCyan: {backgroundColor: '#018fae'},
    bgaqua: {backgroundColor: '#24b3c6'},
    bgBlk: {backgroundColor: '#000000'},
    bgLightGrey: {backgroundColor: '#737373'},
    bgAshW: {backgroundColor: '#e6e6d8'},
    bgAshH:{backgroundColor:'#f9f9f9'},

    //background colors
    bgBlue: {backgroundColor: '#024BD3'},
    bg222: {backgroundColor: '#222'},
    bgBwn: {backgroundColor: '#8B3363'},
    bgGrnA1: {backgroundColor: '#6FBC44'},
    bgGrnF6: {backgroundColor: '#6FBC44'},
    bgGrn72: {backgroundColor: '#60BA72'},
    bgEEE: {backgroundColor: '#EEE'},
    bgFFF: {backgroundColor: '#FFFFFF'},
    bgGrn: {backgroundColor: '#60BA72'},
    bgDash: {backgroundColor: '#dcdcdc'},
    bgColorBlue: {backgroundColor: '#233167'},
    bgLBlueWhite: {backgroundColor: '#F7F7FF'},
    bgLBlueAsh: {backgroundColor: '#EBEDFA'},
    bgLRed: {backgroundColor: '#EB5757'},
    bgLightWhite: {backgroundColor: '#FAFAFA'},
    bgDPink: {backgroundColor: '#E75480'},
    // bgLightWhite: {backgroundColor: '#36A84C'},


    //font-family
    //muli
    ffMregular: {fontFamily: 'Muli-Regular'},
    ffMblack: {fontFamily: 'Muli-Black'},
    ffMbold: {fontFamily: 'Muli-Bold'},
    ffMextrabold: {fontFamily: 'Muli-ExtraBold'},
    ffMlight: {fontFamily: 'Muli-Light'},
    ffMextralight: {fontFamily: 'Muli-ExtraLight'},
    //Lato
    ffLRegular: {fontFamily: 'lato.regular'},
    ffLBold: {fontFamily: 'lato.bold'},
    ffLBlack: {fontFamily: 'lato.black'},
    //Roboto
    ffRBlack: {fontFamily: 'roboto.black'},
    ffRBold: {fontFamily: 'roboto.bold'},
    ffRLight: {fontFamily: 'roboto.light'},
    ffRMedium: {fontFamily: 'roboto.medium'},
    ffRRegular: {fontFamily: 'roboto.regular'},
    ffRThin: {fontFamily: 'roboto.thin'},
    //Rubix
    ffRuBlack: {fontFamily: 'Rubik.Black'},
    ffRuLight: {fontFamily: 'Rubik.Light'},
    ffRuBold: {fontFamily: 'Rubik.Bold'},
    ffRuMedium: {fontFamily: 'Rubik.Medium'},
    ffRuRegular: {fontFamily: 'Rubik.Regular'},

    signature: {
        flex: 1,
        borderColor: '#000033',
        borderWidth: 1,
    },
    signaturebuttonStyle: {
        flex: 1, justifyContent: "center", alignItems: "center", height: 50,
        backgroundColor: "#eeeeee",
        margin: 10
    },

    winWidthBy20: Dimensions.get('window').width - 20,

    //Modal
    modalbgPosition: {flex: 1, position: 'absolute', top: 0, bottom: 0, left: 0, right: 0},
    modalDrawerPoistion: {flex: 1, position: 'absolute', top: 0, bottom: 0, left: 0, right: 0},
    modalImagePopUpSpinner: {
        flex: 1,
        width: Dimensions.get('window').width,
        height: Dimensions.get('window').height,
        position: 'absolute',
        zIndex: 99999,
        backgroundColor: 'rgba(220,220,220,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalfrontPosition: {
        backgroundColor: 'rgba(0, 0, 0 ,0.7)',
        top: 0,
        bottom: 0,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
    },
    modalfrontDarkPosition: {
        backgroundColor: 'rgba(0, 0, 0 ,0.8)',
        top: 0,
        bottom: 0,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
    },
    modalfrontLightTransparent: {
        backgroundColor: 'rgba(0, 0, 0 ,0.3)',
        top: 0,
        bottom: 0,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
    },
    shiftImagePositionAbs: {
        marginHorizontal: 45,
        borderBottomWidth: 2,
        borderBottomColor: '#f5f5f5',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 45
    },
    ordersStatusPositionAbs: {
        marginHorizontal: 45,
        borderBottomWidth: 2,
        borderBottomColor: '#000',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 55
    },
    ProfileScreensStatusPositionAbs: {
        marginHorizontal: 45,
        borderTopWidth: 2,
        borderTopColor: '#f5f5f5',
        position: 'absolute',
        top: 35,
        left: 0,
        right: 0,
        bottom: 0
    },
    profileStatusBar: {
        marginHorizontal: 62,
        borderBottomWidth: 2,
        borderBottomColor: '#fff',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 75
    },
    closeModal:{
        bottom:30,
        position: 'absolute',
        left: 0,
        right: 0,
        justifyContent:'center',
        alignItems:'center'},

    progressBarPositionAbs: {marginHorizontal: 10, position: 'absolute', top: 70, left: 0, right: 0, bottom: 0},
    progressBarStatus: {paddingHorizontal: 15,  top: 0, left: 0, right: 0, bottom: 23},
    progressBarCreateShift:{top: 40,   left: 0,  right: 0,  bottom: 0,  position: 'absolute'},

    //custom modal (Header)
    headerModal: {
        top: 50,
        right:0,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        position:'absolute',
        borderRadius:10,
    },
    headerWithOutBg: {
        // backgroundColor: 'rgba(255,255,255,0.7)',
        top: 0,
        bottom: 0,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
    },
    bottomModalBg: {
        backgroundColor: 'rgba(0, 0, 0 ,0.7)',
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-end',
    },

    //shadow style
    AuthScreenCardshadow: {
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 16,
        shadowRadius: 1.41,
        elevation: 4,
    },
    AuthScreenHeadershadow: {
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 16,
        shadowRadius: 1.41,
        elevation: 4,
    },
    OrdersScreenCardshadow: {
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 60,
        shadowRadius: 1.41,
        elevation: 4,
    },
    TripReportsCardshadow: {
        shadowColor: '#fff',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 60,
        shadowRadius: 1.41,
        elevation: 4,
    },
    TripReportsCardMainshadow: {
shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 60,
        shadowRadius: 1.41,
        elevation: 2,
    },
    ProfileScreenCardshadow: {
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 40,
        shadowRadius: 1.41,
        elevation: 4,
    },
    shadowCard: {
        shadowColor: "#fff",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.20,
        shadowRadius: 1.41,
        elevation: 2,
        marginLeft: 5,
        marginRight: 5,
        borderRadius:0
    },
    profileShadow:{
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.20,
        shadowRadius: 1.41,
        elevation: 5,
    },
    textInputShadow:{
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.20,
        shadowRadius: 1.41,
        elevation: 3,
    },

//Footer Button
    footerSwipeButtonStyles: {
        shadowRadius: 2,
        shadowOffset: {
            width: 0,
            height: -20,
        },
        shadowColor: '#000000',
        elevation: 20,
        marginTop: 10,
        fontFamily: 'Muli-Regular',
        alignItems: 'center',
        paddingVertical: 10,
        backgroundColor: '#FFF'
    },
    footerOrdersSwipeButtonStyles: {
        // shadowRadius: 2,
        // shadowOffset: {
        //     width: 0,
        //     height: -20,
        // },
        // shadowColor: '#000000',
        // elevation: 20,
        marginTop: 10,
        fontFamily: 'Muli-Regular',
        alignItems: 'center',
        paddingVertical: 10,
        backgroundColor: '#FFF'
    },
    footerUpdateButtonStyles: {
        shadowRadius: 2,
        shadowOffset: {
            width: 0,
            height: -20,
        },
        shadowColor: '#000000',
        elevation: 20,
        marginTop: 10,
        fontFamily: 'Muli-Regular',
        padding: 10,
        backgroundColor: '#FFF'
    },
    footerSwipeCreateShiftButtonStyles: {
        shadowRadius: 2,
        shadowOffset: {
            width: 0,
            height: -20,
        },
        shadowColor: '#000000',
        elevation: 20,
        marginBottom: 10,
        fontFamily: 'Muli-Regular',
        alignItems: 'center',
        paddingVertical: 10,
        backgroundColor: '#FFF'
    },

    //Incremnet Decrement Button Styles
    IncDecButtonStyle: {borderWidth: 2, height: 30, width: 30, borderColor: '#b2beb5', fontSize: 18,textAlign: "center",},
    IncDecDisableButtonStyle: {borderWidth: 2, height: 30, width: 30, borderColor: '#b2beb5', fontSize: 18,textAlign: "center",},
    IncrementButton: {
        borderWidth: 2,
        height: 30,
        width: 30,
        // borderColor: '#b2beb5',
        // paddingHorizontal: 12,
        // paddingVertical: 6,
        textAlign: "center",
        fontSize: 18
    },

    TripsIncDecButton: {
        borderWidth: 2,
        height: 50,
        width: 50,
        // borderColor: '#b2beb5',
        // paddingHorizontal: 12,
        // paddingVertical: 6,
        // textAlign: "center",
        fontSize: 18
    },

    ImageUploadActivityIndicator: {
    position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
},    ZoomIconPosition: {
    position: 'absolute',
        // left: 0,
        right: 2,
        top: 2,
        bottom: 0,
        backgroundColor:'#fff',
        width:28,height:28
},    ImageZoomIconPosition: {
    position: 'absolute',
        // left: 0,
        right: 2,
        top: 15,
        bottom: 0,
        backgroundColor:'#fff',
        width:28,height:28
},
    ImageDeleteButtonPosition: {
    position: 'absolute',
        left: 0,
        right: 20,
        top: 30,
        bottom: 0,
},

    //TEXT INPUT STYLE
    TextInputStyle: {
        height: 40,
        backgroundColor: 'rgba(225,225,225,0.2)',
        marginBottom: 20,
        padding: 10,
        color: '#fff',
        fontFamily: 'Muli-Regular'
    },
    containerStyle: {
        flex: 1,
        backgroundColor: '#fff'
    },
    TextImageShadowStyle:{
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: '#b2beb5',
        backgroundColor: '#FFF',
        marginVertical: 5,
        borderRadius: 5,
        paddingVertical: 15,
        paddingHorizontal: 10,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.20,
        shadowRadius: 1.41,
        elevation: 3,
    },

    //Border
    bw0: {borderWidth: 0},
    bw1: {borderWidth: 1},
    bw2: {borderWidth: 2},
    bw3: {borderWidth: 3},
    bw5: {borderWidth: 5},
    br0: {borderRadius: 0},
    br3: {borderRadius: 3},
    br5: {borderRadius: 5},
    br8: {borderRadius: 8},
    br10: {borderRadius: 10,},
    br15: {borderRadius: 15,},
    br20: {borderRadius: 20,},
    br25: {borderRadius: 25,},
    br30: {borderRadius: 30},
    br40: {borderRadius: 40},
    br50: {borderRadius: 50},
    br55: {borderRadius: 55},
    br100: {borderRadius: 100},

    //Image
    headerImg: {width: 20, height: 20, resizeMode: 'contain'},
    H28W28: {width: 28, height: 28},

    imgH25W30: {height: 25, width: 30},

    ImgResizeModeStretch: {resizeMode: "stretch"},
    ImgResizeModeCover: {resizeMode: "cover"},
    ImgResizeModeContain: {resizeMode: "contain"},
    ImgResizeModeRepeat: {resizeMode: "repeat"},
    ImgResizeModeCenter: {resizeMode: "center"},


    winW: Dimensions.get('window').width,
    winH: Dimensions.get('window').height,

    img10: {width: 10, height: 10},
    img20: {width: 20, height: 20},
    img25: {width: 25, height: 25},
    img30: {width: 30, height: 30},
    img35: {width: 35, height: 35},
    img40: {width: 40, height: 40},
    img45: {width: 45, height: 45},
    img50: {width: 50, height: 50},
    img53: {width: 53, height: 53},
    img60: {width: 60, height: 60},
    img70: {width: 70, height: 70},
    img55: {width: 55, height: 55},
    img80: {width: 80, height: 80},
    img87: {width: 87, height: 87},
    img100: {height: 100, width: 100},
    img150: {height: 150, width: 150},
    img200: {width: 200, height: 200},
    img300: {width: 300, height: 300},


    TabBw: {borderBottomWidth: 4, borderBottomColor: '#018fae', marginTop: 5,},
    TabBw1: {borderBottomWidth: 1, borderBottomColor: '#018fae', marginTop: 5,},
brBw1:{borderBottomWidth:2,borderBottomColor:'#b2beb5'},

    // Common usage classes
    jStart: {justifyContent: 'flex-start'},
    jCenter: {justifyContent: 'center'},
    jEnd: {justifyContent: 'flex-end'},
    aitStart: {alignItems: 'flex-start'},
    aitCenter: {alignItems: 'center'},
    aitEnd: {alignItems: 'flex-end'},
    aslStretch: {alignSelf: 'stretch'},
    aslCenter: {alignSelf: 'center'},
    aslStart: {alignSelf: 'flex-start'},
    aslEnd: {alignSelf: 'flex-end'},
    row: {flexDirection: 'row'},
    jSpaceBet: {justifyContent: 'space-between'},
    jSpaceArd: {justifyContent: 'space-around'},
    txtAlignCen: {textAlign: 'center'},
    txtAlignLt: {textAlign: 'left'},
    txtAlignRt: {textAlign: 'right'},
    alignTopCenter: {alignItems: 'flex-start', justifyContent: 'center'},
    alignCenter: {alignItems: 'center', justifyContent: 'center'},
    alignEnd: {alignItems: 'center', justifyContent: 'flex-end'},
    alignEndEnd: {alignItems: 'flex-end', justifyContent: 'flex-end'},
    alignCenterBtm: {alignItems: 'flex-end', justifyContent: 'center'},


    brdrLft1: {borderLeftColor: '#ddd', borderLeftWidth: 1},
    brdr1: {borderColor: '#ddd', borderWidth: 1},
    brdrRt1: {borderRightColor: '#ddd', borderRightWidth: 1},
    brRt1bcAsh: { borderRightWidth: 1,borderRightColor: '#D1D1D1'},
    brdrBtm0: { borderBottomWidth: 0},
    brdrBtm1: {borderBottomColor: '#000', borderBottomWidth: 1},
    brdrBtm2White: {borderBottomColor: '#fff', borderBottomWidth: 2},
    brdrBtm2Red: {borderBottomColor: '#C91A1F', borderBottomWidth: 2},

    // Margins
    Top20: {top: 20},
    m1: {margin: 1},
    m2: {margin: 2},
    m3: {margin: 3},
    m5: {margin: 5},
    m8: {margin: 8},
    m10: {margin: 10},
    m15: {margin: 15},
    m20: {margin: 20},
    m25: {margin: 25},
    m30: {margin: 30},
    m50: {margin: 50},
    m80: {margin: 80},
    mLt0: {marginLeft: 0},
    mLt5: {marginLeft: 5},
    mLt10: {marginLeft: 10},
    mLt15: {marginLeft: 15},
    mLt20: {marginLeft: 20},
    mLt30: {marginLeft: 30},
    mLt40: {marginLeft: 40},
    mLt70minus: {marginLeft: -70},
    mTop10minus: {marginTop: -10},
    mTop30minus: {marginTop: -30},
    mRt5: {marginRight: 5},
    mRt10: {marginRight: 10},
    mRt15: {marginRight: 15},
    mRt30: {marginRight: 30},
    mRt40: {marginRight: 40},
    mTop0: {marginTop: 0},
    mTop3: {marginTop: 3},
    mTop5: {marginTop: 5},
    mTop8: {marginTop: 8},
    mTop10: {marginTop: 10},
    mTop15: {marginTop: 15},
    mTop20: {marginTop: 20},
    mTop30: {marginTop: 30},
    mTop40: {marginTop: 40},
    mTop70: {marginTop: 70},
    mTop80: {marginTop: 80},
    mBtm1: {marginBottom: 1},
    mBtm5: {marginBottom: 5},
    mBtm3: {marginBottom: 3},
    mBtm10: {marginBottom: 10},
    mBtm15: {marginBottom: 15},
    mBtm20: {marginBottom: 20},
    mBtm25: {marginBottom: 25},
    mBtm30: {marginBottom: 30},
    mBtm50: {marginBottom: 50},
    mBtm70: {marginBottom: 70},
    marH1: {marginHorizontal: 1},
    marH2: {marginHorizontal: 2},
    marH3: {marginHorizontal: 3},
    marH5: {marginHorizontal: 5},
    marH10: {marginHorizontal: 10},
    marH15: {marginHorizontal: 15},
    marH20: {marginHorizontal: 20},
    marH25: {marginHorizontal: 25},
    marH30: {marginHorizontal: 30},
    marH35: {marginHorizontal: 35},
    marH40: {marginHorizontal: 40},
    marH50: {marginHorizontal: 50},
    marH60: {marginHorizontal: 60},
    marH75: {marginHorizontal: 75},
    marH67: {marginHorizontal: 67},
    marV0: {marginVertical: 0},
    marV1: {marginVertical: 1},
    marV3: {marginVertical: 3},
    marV5: {marginVertical: 5},
    marV7: {marginVertical: 7},
    marV10: {marginVertical: 10},
    marV15: {marginVertical: 15},
    marV20: {marginVertical: 20},
    marV25: {marginVertical: 25},
    marV30: {marginVertical: 30},
    marV40: {marginVertical: 40},
    marV50: {marginVertical: 50},
    marV70: {marginVertical: 70},
    marV80: {marginVertical: 80},
    marV100: {marginVertical: 100},
    marV150: {marginVertical: 150},

    //paddings
    p1: {padding: 1},
    p2: {padding: 2},
    p3: {padding: 3},
    p5: {padding: 5},
    p10: {padding: 10},
    p15: {padding: 15},
    p20: {padding: 20},
    p30: {padding: 30},
    p40: {padding: 40},
    pRight3: {paddingRight: 3},
    pRight5: {paddingRight: 5},
    pRight10: {paddingRight: 10},
    pRight15: {paddingRight: 15},
    pRight20: {paddingRight: 20},
    pLeft5: {paddingLeft: 5},
    pLeft10: {paddingLeft: 10},
    pLeft15: {paddingLeft: 15},
    pLeft20: {paddingLeft: 20},
    pLeft25: {paddingLeft: 25},
    pLeft30: {paddingLeft: 30},
    pTop2: {paddingTop: 2},
    pTop3: {paddingTop: 3},
    pTop5: {paddingTop: 5},
    pTop10: {paddingTop: 10},
    pTop15: {paddingTop: 15},
    pTop20: {paddingTop: 20},
    pTop40: {paddingTop: 40},
    pTop45: {paddingTop: 45},
    pTop50: {paddingTop: 50},
    pTop55: {paddingTop: 55},
    pTop60: {paddingTop: 60},
    pBtm3: {paddingBottom: 3},
    pBtm5: {paddingBottom: 5},
    pBtm10: {paddingBottom: 10},
    pBtm18: {paddingBottom: 18},
    pBtm20: {paddingBottom: 20},
    padV3: {paddingVertical: 3},
    padV5: {paddingVertical: 5},
    padV6: {paddingVertical: 6},
    padV7: {paddingVertical: 7},
    padV8: {paddingVertical: 8},
    padV10: {paddingVertical: 10},
    padV15: {paddingVertical: 15},
    padV20: {paddingVertical: 20},
    padV30: {paddingVertical: 30},
    padV40: {paddingVertical: 40},
    padV50: {paddingVertical: 50},
    padV70: {paddingVertical: 70},
    padH1: {paddingHorizontal: 1},
    padH2: {paddingHorizontal: 2},
    padH5: {paddingHorizontal: 5},
    padH10: {paddingHorizontal: 10},
    padH15: {paddingHorizontal: 15},
    padH20: {paddingHorizontal: 20},
    padH22: {paddingHorizontal: 22},
    padH25: {paddingHorizontal: 25},
    padH30: {paddingHorizontal: 30},
    padH35: {paddingHorizontal: 35},
    padH40: {paddingHorizontal: 40},
    padH50: {paddingHorizontal: 50},
    padH70: {paddingHorizontal: 70},
    padH80: {paddingHorizontal: 80},


    // Flex
    flex1: {flex: 1},
    flexWrap: {flexWrap: 'wrap'},

    //fontSizes
    f8: {fontSize: 8},
    f10: {fontSize: 10},
    f12: {fontSize: 12},
    f14: {fontSize: 14},
    f16: {fontSize: 16},
    f17: {fontSize: 17},
    f18: {fontSize: 18},
    f20: {fontSize: 20},
    f21: {fontSize: 21},
    f22: {fontSize: 22},
    f24: {fontSize: 24},
    f25: {fontSize: 25},
    f28: {fontSize: 28},
    f30: {fontSize: 30},
    f36: {fontSize: 36},
    f40: {fontSize: 40},
    f50: {fontSize: 50},


    //fontWeight
    fWbold: {fontWeight: 'bold'},
    fItalic: {fontStyle: 'italic'},

    backgroundImg: {flex: 1, width: null, height: null},


    postItemUploadBox: {height: 200, backgroundColor: '#EEE'},
    postItemImgBox: {width: 80, height: 80, backgroundColor: '#EEE', zIndex: -1},
    bgAmyPurple: {backgroundColor: '#8B3363'},
    addPostImgWrap: {
        backgroundColor: '#C01530',
        justifyContent: 'center',
        alignItems: 'center',
        width: 20,
        height: 20,
        borderRadius: 20,
        position: 'absolute',
        top: -10,
        right: 0
    },
    radioStyle: {
        borderWidth: 1,
        borderColor: '#DDD',
        borderRadius: 20,
        width: 20,
        height: 20,
        justifyContent: 'center',
        alignItems: 'center'
    },
    radioActiveStyle: {backgroundColor: '#8B3363', width: 12, height: 12, borderRadius: 12},
    checkboxStyle: {
        borderWidth: 1,
        borderColor: '#999',
        borderRadius: 4,
        width: 20,
        height: 20,
        justifyContent: 'center',
        alignItems: 'center'
    },
    checkboxActiveStyle: {backgroundColor: '#8B3363', width: 12, height: 12, borderRadius: 12},

    cText: {backgroundColor: 'transparent', fontSize: 14, color: '#666'},
    inputStyle: {height: 45, marginVertical: 5},

    authBgImg: {flex: 1, width: undefined, height: undefined},
    authLayout: {position: 'absolute', top: 0, left: 0, right: 0, bottom: 0},
    authLogo: {width: 190, height: 60, resizeMode: 'contain'},
    authFGiconImg: {height: 40, resizeMode: 'contain', marginBottom: 10},
    authScreenBtn: {backgroundColor: '#6fbe42', paddingHorizontal: 20, paddingVertical: 20, alignItems: 'center'},

    //changed by sharath
    popContainer: {backgroundColor: 'rgba(0, 0, 0, 0.75)', flex: 1, justifyContent: 'center', padding: 20},
    mainContainer: {backgroundColor: '#FFF', width: 250, position: 'absolute', top: 0, left: 0, right: 0, bottom: 0},
    basicContainer: {
        borderRadius: 10,
        backgroundColor: '#FFF',
        position: 'absolute',
        top: 20,
        left: 20,
        right: 20,
        bottom: 20
    },
    filterContainer: {backgroundColor: '#FFF', position: 'absolute', top: 0, left: 0, right: 0,},

    popText: {fontSize: 16, color: '#999'},
    popTitle: {fontSize: 16, color: '#3C4556', marginBottom: 10},
    popButton: {
        backgroundColor: '#8b3363', paddingVertical: 10, alignItems: 'center',
        borderRadius: 5,
    },

    //custom styles added by sharath
    posRel: {flex: 1, position: 'relative', top: 0, bottom: 0, left: 0, right: 0},
    headContainer: {
        backgroundColor: '#8b3363',
        flexDirection: 'row',
        paddingHorizontal: 20,
        paddingVertical: 20,
        paddingTop: Platform.OS === 'ios' ? 40 : 10
    },
    itemsList: {borderBottomWidth: 1, paddingVertical: 10, borderBottomColor: 'gray'},
    categoryImg: {borderRadius: 50, margin: 10, width: 100, height: 100},
    productImg: {width: 25, height: 25, resizeMode: 'contain'},
    productOneImg: {width: 40, height: 40, resizeMode: 'contain'},
    prodActionImg: {position: 'absolute', top: 0, left: 0, backgroundColor: 'rgba(0,0,0,0.3)', width: 50, height: 140},
    homeGenText: {color: '#ffffff', fontSize: 30, fontWeight: 'bold', position: 'absolute', top: 130, left: 30},
    menuProfileImg: {width: 100, height: 100, borderRadius: 50, backgroundColor: 'grey'},
    menuProfEditImg: {width: 20, height: 20},
    btmMenuImg: {width: 20, height: 20, resizeMode: 'contain'},
    btmCenterMenuImg: {width: 40, height: 40, resizeMode: 'contain'},
    editIconPos: {position: 'absolute', right: 0, top: 5},
    menuProfContainer: {height: 200, width: 250, backgroundColor: '#8b3363'},
    menuItemIcon: {width: 25, height: 25, resizeMode: 'contain'},
        shadow: {
        backgroundColor: 'grey',
        shadowColor: '#999',
        shadowOpacity: 0.3,
        shadowRadius: 2,
        shadowOffset: {width: 0, height: 2}
    },
    searchCat: {width: 75, height: 75, borderRadius: 37, margin: 5, backgroundColor: 'grey'},

    // styles by vignesh
    tabStyle: {paddingVertical: 10, borderBottomWidth: 5, borderBottomColor: '#6FBC44', paddingHorizontal: 15},
    tabActive: {borderBottomColor: 'white'},

    plainBtn: {
        borderWidth: 1,
        borderColor: '#EEE',
        paddingHorizontal: 8,
        paddingVertical: 5,
        borderRadius: 2,
        justifyContent: 'center',
        alignItems: 'center'
    },
    saveItemProductImg: {width: 80, height: 80, resizeMode: 'cover', margin: 10, borderRadius: 40},
    saveItemAddBasketBtn: {backgroundColor: '#8B3363'},
    pickerPopContainer: {
        position: 'absolute',
        top: 30,
        left: 25,
        right: 20,
        paddingVertical: 10,
        paddingHorizontal: 20
    },
    closePostPopButton: {
        backgroundColor: '#8B3363',
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderRadius: 2,
        justifyContent: 'center',
        alignItems: 'center',
        width: 80
    },

    appbarBorder: {borderBottomWidth: 1, borderBottomColor: '#ccc'},
    keyBalanceBuyItBtn: {backgroundColor: '#8B3363', paddingHorizontal: 40, marginVertical: 10, paddingVertical: 15},
    publicProfileCommentImg: {width: 60, height: 60, marginHorizontal: 15, borderRadius: 160},
    publicProfileUserDetails: {backgroundColor: '#8B3363', paddingHorizontal: 20, paddingTop: 40, paddingBottom: 5},
    publicProfileImg: {width: 70, height: 70, borderRadius: 35},
    publicProfileCloseBtn: {position: 'absolute', top: 20, right: 10},
    publicProfileEditIcon: {width: 20, height: 20, borderRadius: 10, position: 'absolute', top: 5, right: -5},
    headerCounts: {
        width: 20,
        height: 20,
        position: 'absolute',
        right: 5,
        padding: 2,
        borderRadius: 10,
        borderColor: "#60BA72",
        borderWidth: 1,
    },
    brdrLft: {borderLeftColor: '#ddd', borderLeftWidth: 1},
    brdr: {borderColor: '#ddd', borderWidth: 1},
    brdrRt: {borderRightColor: '#ddd', borderRightWidth: 1},
    brdrBtm: {borderBottomColor: '#F6F6F6', borderBottomWidth: 3},

    notifyMainContainer: {backgroundColor: '#FFF', position: 'absolute', top: 20, left: 20, right: 20, borderRadius: 5},

    popButtonLeft: {paddingVertical: 8, alignItems: 'center', paddingHorizontal: 15},
    popButtonRight: {paddingVertical: 8, alignItems: 'center', paddingHorizontal: 15},

    footerTabCounts: {width: 20, height: 20, borderRadius: 10, position: 'absolute', top: 0, right: 0},
    logoView: {marginBottom: 40, width: 180, height: 180},
    brdTopRad10: {borderTopLeftRadius: 10, borderTopRightRadius: 10},


    personalPreferenceProfileEditBtn: {
        position: 'absolute',
        top: 5,
        right: '30%',
        borderWidth: 1,
        borderColor: '#999',
        borderRadius: 20
    },
    featuredBtnStyle: {borderRadius: 15, paddingHorizontal: 12},
    brdPurple: {borderColor: '#8B3363'},
    brdWidth1: {borderWidth: 1},
    brdWidthDot7: {borderWidth: 0.7},
    width80: {width: 80},
    width120: {width: 120},
    width150: {width: 150},
    productHistoryModal: {
        position: 'absolute',
        top: 30,
        bottom: 30,
        left: 10,
        right: 10,
        backgroundColor: '#F5F5F5',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10
    },
    grnBtn: {borderColor: "#60BA72", borderWidth: 1, borderRadius: 5},

    walkThroughStyles: {
        flex: 1,
        width: Dimensions.get('window').width,
        height: Dimensions.get('window').height,
        position: 'absolute',
        zIndex: 99999,
        backgroundColor: 'rgba(0,0,0,0.7)',
    },

    walkThroughStylesInsidePoolChat: {
        flex: 1,
        width: Dimensions.get('window').width,
        height: Dimensions.get('window').height,
        position: 'absolute',
        zIndex: 99999,
    },
};

// IOS STYLES
const IosStyles = {
    regText1: {fontSize: 20, color: '#000', fontWeight: 'bold'},
    regText2: {fontSize: 16, color: '#000'},

};
const Styles = Platform.OS === 'ios' ? IosStyles : AndroidStyles;

export {Styles};
